### ISSUE TITLE
Does not work on Sublime 3, Mas OS X Mavericks

### ISSUE THREAD

**Issue by matijap** [danielfrey/sublime-cucumber-step-finder#23]
I have installed the plugin, but pressing ctrl + y (or any other keyboard shortcut) does not perform anything. Even when i try to invoke "cucumber step finder" through Find -> Find Cucumber Step it does nothing.

**Comment by danielfrey** [comment]
On Mac OS X you should press cmd+y, not ctrl+y. But the menu entry should work.
Do you see any errors in the console?
Are your step files in the directory configured in the settings? See https://github.com/danielfrey/sublime-cucumber-step-finder#configuration

**Comment by matijap** [comment]
Thank you for response.
I have tried both ctrl and cmd, and it does not work. Menu entry doesn't work event it should.
I can see no errors in console. When i click menu item, nothing new pops up in a console.
Also, only thing that i configured is:
{
    "cucumber_step_pattern"   :   ".*\\.rb"
}
Which I put in Settings - User file.

**Comment by danielfrey** [comment]
With your pattern it will find all ruby files, which will fail (given your backslashes are correct). In Cucumber-Rails you should name your step-files by convention like e.g "form_steps.rb".
If you can't identify thr files properly with a regular expression, the plugin will fail.
Please read the configuration section carefully and set your setting appropriate.

In your user file, did you set the correct key?

``` json
    "CucumberStepFinder":
    {
                "cucumber_features_path"  :  "features",
                "cucumber_step_pattern"   :  ".*_steps.*\\.rb"
    }
```

Be careful and set the backslashes correct. I miss the second backslash in your regex. This won't work at all. Test your regex with a tool if your not familiar with regex: http://rubular.com/

I close this issue since it is a specific configuration configuration problem. It has nothing to do with Mavericks and the title is misleading.
